### PR TITLE
fix nav-v4 support

### LINKED ISSUE #146: RINEX v4: Missing GPS CNAV fields
I have some time to read through the new `orbits.json` file, and I am comparing it to the modified one I was using from a few months ago and making notes of anything I spot.

GPS CNV2:
- Missing ISCs for L1C:
image
- Might need to add two spares here as last two fields are from the next line, for some reason they don't document that

QZSS CNV2:
- Missing ISCs for L1C:
image
- Might need to add two spares here as last two fields are from the next line, for some reason they don't document that

BDS CNV1:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
image
- `b1c` - it might be clearer that this field has special meaning by adding `integrity`, or `if` to the name
- Missing spare between ISC and TGD:
image

BDS CNV2:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
image
- Replace `isc_b1cd` with a spare, then add ISC B2ad between the spare and TGDs:
image
- Rename `b1c` to `b2a_b1c`, possibly adding integrity to name like suggestion above:
image

BDS CNV3:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
image
- Delete the `isc_` and `tgd_` values - should go from `sisa1_oc2` to `sismai`:
image
- Rename `b1c` to `b2b`, possibly adding integrity to name like suggestion above
- Replace `iodc` with `tgd_b2bi`
- Remove the last two spares and `iode`

To help with the test coverage I have attached the IGS RINEX v4 "BRDC" file I was using earlier in the year. This is a useful file as it has every type of NAV data except for GPS CNV2, and BDS CNV3.
[BRD400DLR_S_20230710000_01D_MN.rnx.gz](https://github.com/georust/rinex/files/12462707/BRD400DLR_S_20230710000_01D_MN.rnx.gz)

I will see if there is the missing ones in any newer files.

### PR DESCRIPTION
**Pull request by gwbres**
- [x] Fix #146 
- [x] Introduce new `test_resource/NAV/V4` file and associated test bench
- [x] Test NAV V4 STO, ION and  EOP logical conditions on all files
- [x] Introduce first EOP tests

### CODE REVIEW

File: rinex/tests/parsing.rs [hunk 1]
```diff
@@ -42,6 +43,89 @@ mod test {
                             assert!(rinex.is_navigation_rinex());
                             assert!(rinex.epoch().next().is_some());
                             assert!(rinex.epoch().count() > 0); // all files have content
+                                                                /*
+                                                                 * Verify ION logical correctness
+                                                                 */
+                            for (_, (msg, sv, ion_msg)) in rinex.ionosphere_models() {
+                                if sv.constellation == Constellation::GPS {
```
Comment (lnicola) [inline rinex/tests/parsing.rs:50]: Could use a `match` here.

File: rinex/tests/parsing.rs [hunk 2]
```diff
@@ -42,6 +43,89 @@ mod test {
...
+                                } else if sv.constellation == Constellation::QZSS {
+                                    assert!(
+                                        ion_msg.as_klobuchar().is_some(),
+                                        "only Kb models provided by QZSS vehicles"
+                                    );
+                                } else if sv.constellation == Constellation::BeiDou {
+                                    match msg {
+                                        NavMsgType::D1D2 => {
+                                            assert!(
+                                                ion_msg.as_klobuchar().is_some() == true,
```
Comment (lnicola) [inline rinex/tests/parsing.rs:64]:
```suggestion
                                                ion_msg.as_klobuchar().is_some(),
```

File: rinex/tests/parsing.rs [hunk 3]
```diff
@@ -42,6 +43,89 @@ mod test {
...
+                                        sv.constellation
+                                    );
+                                }
+                            }
+                            /*
+                             * Verify EOP logical correctness
+                             */
+                            for (_, (msg, sv, _)) in rinex.earth_orientation() {
+                                assert!(
+                                    (sv.constellation == Constellation::GPS)
```
Comment (lnicola) [inline rinex/tests/parsing.rs:104]: Could do `matches!(sv.constellation, Constellation::GPS | Constellation::QZSS | Constellation::IRNSS | Constellation::BeiDou)` instead.

File: rinex/tests/parsing.rs [hunk 4]
```diff
@@ -42,6 +43,89 @@ mod test {
...
+                                    "bad msg identified for GPS vehicle: {}",
+                                    msg
+                                );
+                            }
+                            /*
+                             * Verify STO logical correctness
+                             */
+                            for (_, (msg, sv, _)) in rinex.system_time_offset() {
+                                assert!(
+                                    (msg == NavMsgType::LNAV)
```
Comment (lnicola) [inline rinex/tests/parsing.rs:119]: `matches!` works here, too.

**Review by lnicola — APPROVED** [review]

File: rinex/tests/parsing.rs (hunk 4 above)
Comment (gwbres) [reply rinex/tests/parsing.rs]: applied, but in the following form,  
because I like having meaningful panic messages that help debug what went wrong.
`matches!` does not allow for a panic message

```rust
match var {
    cond1 | cond2 | cond3 => {}, 
    _ => panic!("oops"),
}
```

Comment (lnicola) [reply rinex/tests/parsing.rs]: You can use a `match` like in your snippet, or keep doing `assert!(matches!(..., ...), ...)`.

Comment (gwbres) [reply rinex/tests/parsing.rs]: Oh I see, assert! on matches! which is then a boolean condition. Will try next time
